# This is a basic workflow that is manually triggered to test the build & unit test process 
name: Test Build
on: workflow_dispatch
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      REPO_NAME: terraform-provider-incapsula
    steps:
    - name: Install Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: Setup env
      run: |
        export GOPATH=$HOME/go
        echo "GOPATH=$GOPATH" >> $GITHUB_ENV
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/terraform-providers/$REPO_NAME
        mv $(pwd)/* $GOPATH/src/github.com/terraform-providers/$REPO_NAME
    - name: Test
      run: |
        cd $GOPATH/src/github.com/terraform-providers/$REPO_NAME
        make test
    - name: Build
      id: build
      run: |
        cd $GOPATH/src/github.com/terraform-providers/$REPO_NAME
        make build-github
        ls -l $GOPATH/bin
        echo ::set-output name=ARTIFACT_PATH::$GOPATH/bin
        echo ::set-output name=ARTIFACT_NAME::terraform-provider-incapsula